- .env.example
- package-lock.json
- src/env.js
- src/server/auth.ts
closes/addresses issue #3 
- added Google and Github providers to NextAuth
- removed Discord provider
works (google):
> add google and github nextauth providers, remove discord

- src/server/api/routers/application.ts
closes/addresses issue #9 
- added get application query
> add get application query

- README.md
- package-lock.json
- package.json
- src/server/db/index.ts
- src/server/db/schema.ts
- src/server/db/seed/application-seeder.ts
- src/server/db/seed/index.ts
- src/server/db/seed/preregistration-seeder.ts
- src/server/db/seed/user-seeder.ts
> Database Seed Script

- .github/workflows/test-and-build.yml
- drizzle.config.ts
- package-lock.json
- package.json
- src/pages/api/preregistration/all.ts
- src/pages/index.tsx
- update to drizzle-kit v0.21 so that drizzle studio works
> Update to drizzle-kit v0.21

- drizzle.config.ts
- Remove dotenv from `drizzle.config.ts`
> Remove dotenv from `drizzle.config.ts`

- src/components/ui/calendar.tsx
- src/components/ui/form.tsx
> linting fixes

- src/server/api/routers/auth.ts
closes/addresses #35 
- Added validation and error handling for email and password inputs
> add input validation credentials

- drizzle/0005_furry_kingpin.sql
- drizzle/meta/0005_snapshot.json
- drizzle/meta/_journal.json
- src/components/preregistration-form.tsx
- src/components/ui/button.tsx
- src/pages/_app.tsx
- src/pages/internal/index.tsx
- src/pages/mock-application.tsx
- src/server/api/routers/preregistration.test.ts
- src/server/db/schema.ts
- src/server/db/seed/preregistrationSeeder.ts
- tailwind.config.ts
addresses #57 
- added preregistration form component
> Preregistration Form Component

- .github/workflows/prettier.yml
- .github/workflows/test.yml
- src/pages/api/application/all.ts
- src/pages/internal/index.tsx
- src/pages/internal/test-password-reset.tsx
- src/server/api/routers/preregistration.ts
closes #67 
- change `test-and-build` action to only run tests and not build, is now `test`
- change `prettier` action to now write changes instead of checking styling
- change `prettier` action to run at commits to PRs instead of on review request
- remove some unused imports
> Change `prettier` to commit, change `test-and-build` to just `test`

- src/pages/index.tsx
- (added x component)
- (added y function to a service on our backend)
> Update date on promo site

- src/pages/_app.tsx
- (added x component)
- (added y function to a service on our backend)
> remove console log *oops*

- drizzle/0006_many_chronomancer.sql
- drizzle/meta/0006_snapshot.json
- drizzle/meta/_journal.json
- src/schemas/review.ts
- src/server/api/routers/reviews.ts
- src/server/db/schema.ts
closes/addresses #49 
- created reviews router with save mutation
> save review mutation

- src/server/api/routers/reviews.ts
Addresses issue  #77 
Added a router, querying  all reviews related to an organizer
> Get all reviews

- .github/workflows/prettier.yml
- .github/workflows/test.yml
- add dev branch for actions pull request trigger
- add workflow-dispatch as another trigger (for running manually)
> Fix Github Actions

- src/components/ui/checkbox.tsx
closes #105
-hardcoded changes into shadcn component since there are no variants (if one-off changes needed we can just use classname?)
> Checkbox Component

- src/components/apply/navigation.tsx
- src/components/ui/button.tsx
- src/components/ui/calendar.tsx
- src/components/ui/date-picker.tsx
- src/components/ui/input.tsx
- src/components/ui/textarea.tsx
- src/pages/internal/test-ui.tsx
- src/styles/globals.css
closes #102 
- styled Calendar and DatePicker components to match the app portal design
- modified the Calendar to include month and year dropdowns
- modified Button, Input, and TextArea components to match the design
- change colours in globals.css to match the design
> Date Picker Component

- src/components/apply/saved-indicator.tsx
closes #130 
- fixes date formatting 
before:
after: 
> Fix Last Saved Date Formatting

- src/components/apply/form/agreements-form.tsx
- src/components/hooks/use-auto-save.ts
- src/pages/register.tsx
- src/schemas/application.ts
- src/server/db/seed/applicationSeeder.ts
closes #116 
- add agreement form
- did *not* add `select all` checkbox since the hacker should probably actually read every line
> Agreements Form

- src/components/ui/radio-group.tsx
- src/pages/internal/test-ui.tsx
closes #103 
- add RadioButtonItem component based off of the figma design
- add example to test-ui page
> [App Portal] Radio Button Item

- package-lock.json
- src/components/ui/stamp.tsx
- src/pages/submitted.tsx
- tailwind.config.ts
closes #119 
- Added submitted page
> Add `/submitted` page

- src/components/apply/avatar.tsx
- src/pages/dashboard.tsx
- src/pages/internal/review.tsx
- src/pages/internal/test-password-reset.tsx
- src/pages/login.tsx
- src/server/db/schema.ts
- src/utils/redirect.ts
closes #136 
- added hacker dashboard
- note that there are some status inconsistencies between schema and figma design
> Hacker Dashboard

- src/schemas/application.ts
- src/server/api/routers/application.test.ts
- src/server/api/routers/application.ts
- src/server/db/seed/applicationSeeder.ts
- fix undefined issue with github and linkedin links
- fix phone number, optional fields, and empty string issues in applicationSubmitSchema
> [App Portal] Handle Empty String and Application Submit Schema

- src/components/ui/select.tsx
- src/pages/internal/test-ui.tsx
- src/styles/globals.css
closes #106 
- style select component
> Style Select Component

- src/components/apply/menu.tsx
- src/pages/apply.tsx
closes #161
- fixes overflow scrolling
> Fix Application Scrolling Behaviour

- src/components/promo/header.tsx
- remove a bunch cringe of margin styling
- make focus styling better for links!
> [Promo Site V2] Improve Navbar

- src/components/promo/Hero.tsx
- remove extra hw logo on hero component
> remove extra hw logo

- src/components/apply/navbar.tsx
- src/components/apply/passport.tsx
- src/pages/apply.tsx
- src/pages/dashboard.tsx
- src/pages/login.tsx
- src/pages/register.tsx
closes #166 
- hate these shitty clouds man ☁️🌃
> Add backgrounds to apply, dashboard, login, register

- package-lock.json
- package.json
- src/components/apply/form/application-form.tsx
- src/components/apply/form/basics-form.tsx
- src/components/apply/form/info-form.tsx
- src/components/apply/form/review-form.tsx
- src/components/apply/menu.tsx
- src/components/apply/navigation.tsx
- src/components/ui/separator.tsx
- src/constants/apply.ts
- src/pages/apply.tsx
- src/schemas/application.ts
closes #118 
- add review step
- fix applicationSubmitSchema
- make navigation buttons on desktop fixed
- fix SavedIndicator positioning on mobile when saving/pending
- make mobile menu more accessible by using Buttons and using two DrawerTrigger components
> [App Portal] Review Step

- src/components/apply/form/review-form.tsx
- fix phone number error in review step
> Fix phone number error in Review Step

- src/pages/login.tsx
removes remember me checkbox on login
> Remove Remember Me

- src/pages/internal/stats.tsx
- src/server/api/routers/application.ts
> App Stats Page for organizer

- package-lock.json
- package.json
- src/components/columns.tsx
- src/components/data-table.tsx
- src/components/ui/data-table.tsx
- src/components/ui/table.tsx
- src/pages/internal/dashboard.tsx
- src/server/api/routers/review.ts
closes/addresses #212 
- add `/internal/dashboard` page for reviews
- add table showing all previous and current reviews you've done
- add edit button linked to `/internal/review?applicant=<id>`
> Add internal review dashboard

- src/lib/date.ts
> extend deadline

- src/lib/date.ts
- (added x component)
- (added y function to a service on our backend)
> fix deadline

- src/pages/dashboard.tsx
- src/utils/redirect.ts
- (added x component)
- (added y function to a service on our backend)
> change redirect for dashboard

- src/components/promo/About.tsx
- src/styles/globals.css
> Smooth Scroll and About Page Link

- src/components/columns.tsx
- src/components/ui/data-table.tsx
- src/components/ui/table.tsx
- src/pages/internal/dashboard.tsx
- src/pages/internal/review.tsx
- src/server/api/routers/review.ts
> Reviewer Leaderboard

- src/components/columns.tsx
- src/components/ui/data-table.tsx
- src/components/ui/table.tsx
- src/pages/internal/dashboard.tsx
- src/pages/internal/review.tsx
improvements for mobile users (me)
> Mobile Fixes

- src/components/cloud-background.tsx
- src/pages/apply.tsx
- src/pages/dashboard.tsx
- src/pages/forgot-password.tsx
- src/pages/internal/dashboard.tsx
- src/pages/login.tsx
- src/pages/not-verified.tsx
- src/pages/register.tsx
- src/pages/reset-password.tsx
- src/pages/submitted.tsx
- src/pages/verify.tsx
> Componentize Cloud Backgrounds

- src/pages/internal/review.tsx
- src/schemas/review.ts
> Fix Review Form Field Reset

- src/pages/internal/review.tsx
another minor mobile fix
also use exported bg component for review page
> Minor Mobile Fix

- src/pages/internal/review.tsx
> Fix Scrolling Cut Off

- .github/pull_request_template.md
> Fix PR Template to Close Issues

- src/pages/internal/dashboard.tsx
add a case to handle when there are no more applications to review
> Handle No More Reviews

- src/components/promo/Hero.tsx
- src/components/promo/header.tsx
- src/pages/dashboard.tsx
> Apps Closed Text

- src/components/live/sidebar.tsx
- src/components/live/topbar.tsx
- src/pages/live.tsx
> Hacker Portal Responsive Side/Topbar

- src/components/live/mentors.tsx
- src/constants/mentors.ts
- src/pages/live.tsx
> Hacker Portal Mentors

- package-lock.json
- package.json
- src/components/live/faq.tsx
closes #254 
- created responsive layout for FAQs on the live site (need to update actual FAQs)
> Live Site FAQ page

- src/components/live/home.tsx
> Hacker Portal Home Page Responsive Fix

- src/server/api/routers/auth.createEndpoint.test.ts
> Auth create endpoint unit testing

- src/server/api/routers/auth.test.ts
> Auth `reset` endpoint tests

- src/server/api/routers/auth.test.ts
closes (#292)
- Wrote test suite for the auth.ts checkVerify function
- checks if verification status is correct & throws error if not logged in
@hunterchen7 @liuwllm
> added checkVerified test suite

- src/server/api/routers/review.ts
closes #323 
Changed hw11 db query to hw to match the schema
@hunterchen7 @liuwllm
> fixed table query inconsistency

- src/server/api/routers/auth.test.ts
closes #296 
- Wrote test suite for the auth.ts checkValidToken function
- checks if token exists, token is expired, and if the token validates properly 
@hunterchen7 @liuwllm
> Wrote checkValidToken test suite

- src/components/promo/Hero.tsx
shrink for small and add padding
> Mobile Promo Fix (#347)

- README.md
Added deepwiki embed in readme
closes (#333)
- added deepwiki embed
@hunterchen7 @liuwllm
> Update README.md to include deepwiki embed

- LICENSE
- package.json
> MIT License

- src/components/promo/about/index.tsx
- make speech bubble have proper padding
> Fix Speech Bubble for About Section
